Sprint3
ClevertecFrontendLab/DmitryKhiliuk pull request #2
Opened 2023-02-16 18:26 UTC by DmitryKhiliuk

2023-02-16 18:28 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676572133/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676572133/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676572133/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676572133/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676572133/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676572133/main-loading.png)

2023-02-16 18:50 UTC, klichkovskiy requested changes
Пересмотри еще раз как должно быть на макете!

2023-02-16 18:50 UTC, klichkovskiy commented on src/redux/book-reducer.ts
> +    } catch (err:any) {
Если пришла ошибка - не нужно отрисовывать книгу. Нужны только хлебные крошки, с указанием жанра  данной книги
![image](https://user-images.githubusercontent.com/62481116/219456896-b9ef0ab7-53ae-4ab8-a6c1-b415d5182d6f.png)

2023-02-16 18:50 UTC, klichkovskiy commented on src/redux/book-reducer.ts
> +    dispatch(setAppStatusAC({status: 'loading'}))
Если ты грузишь книгу, то ничего предварительно отрисовывать не нужно
![image](https://user-images.githubusercontent.com/62481116/219457378-a0246002-2789-4f7d-9ef6-e4f2f4fc08f1.png)

2023-02-16 18:50 UTC, klichkovskiy commented on src/components/display-view/display-view.tsx
> +        </button> */
удали закомментированные фрагменты

2023-02-16 18:50 UTC, klichkovskiy commented on src/env.d.ts
> +} */
удали закомментированные фрагменты

2023-02-16 18:50 UTC, klichkovskiy commented on src/components/card/card.tsx
> +                        <img src={image ? (`https://strapi.cleverland.by${ image.url}`) : cat}
Так не делается! Перечитай инструкцию. Ты же получаешь книги. Ну так от туда и забирай данные!

2023-02-16 18:50 UTC, klichkovskiy commented on src/components/card/card.tsx
> +                        <div><img src={image ? (`https://strapi.cleverland.by${ image.url}`):cat} alt="img"/></div>
Так нельзя!

2023-02-16 18:50 UTC, klichkovskiy commented on src/components/header/header.module.scss
> +        //position: relative;
удали закомментированные фрагменты

2023-02-16 18:50 UTC, klichkovskiy commented on src/components/slider/mobile-slider.tsx
> +                            <img src={(`https://strapi.cleverland.by${item.url}`)} alt="product images"/>
Так нельзя!

2023-02-16 18:50 UTC, klichkovskiy commented on src/components/slider/slider.tsx
> +                            <img src={(`https://strapi.cleverland.by${item.url}`)} alt="product images" />
Так нельзя!

2023-02-16 18:50 UTC, klichkovskiy commented on src/pages/book/book-page.module.scss
> +                    //margin-right: 30px;
удали закомментированные фрагменты

2023-02-16 18:50 UTC, klichkovskiy commented on src/pages/main/main-page.module.scss
> +    //position: relative;
удали закомментированные фрагменты

2023-02-16 18:50 UTC, klichkovskiy commented on src/redux/books-reducer.ts
> +    } catch (err:any) {
никаких any

2023-02-16 20:39 UTC, DmitryKhiliuk commented on src/components/card/card.tsx
> +                        <img src={image ? (`https://strapi.cleverland.by${ image.url}`) : cat}
Я не совсем понял. Нельзя в пропсах книгу передавать, нужно селектором ее выдергивать?

2023-02-17 07:33 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676619189/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676619189/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676619189/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676619189/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676619189/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676619189/main-loading.png)

2023-02-17 07:40 UTC, klichkovskiy requested changes

2023-02-17 07:40 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +                <div className={styles.breadCrumbs}>
![image](https://user-images.githubusercontent.com/62481116/219580226-d00d0630-478c-4472-b25b-21034bf3635a.png)
А где жанр?

2023-02-17 07:40 UTC, klichkovskiy commented on src/components/card/card.tsx
> +                        <img src={image ? (`https://strapi.cleverland.by${ image.url}`) : cat}
Вместо https://strapi.cleverland.by используй константу HOST и так по всему приложению (если у тебя хост поменяется ты просто поменяешь в одном месте)

2023-02-17 07:40 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +                <div className={styles.breadCrumbs}>
![image](https://user-images.githubusercontent.com/62481116/219581090-61d14694-e634-4f73-9471-1ec8b455d348.png)
Видны хлебные крошки при загрузке

2023-02-17 07:40 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +                <div className={styles.breadCrumbs}>
![image](https://user-images.githubusercontent.com/62481116/219581201-dca80f70-8696-4a7a-8d3f-9db2217c6572.png)
Хлебные крошки сломались(

2023-02-17 20:35 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676666109/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676666109/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676666109/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676666109/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676666109/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1676666109/main-loading.png)

2023-02-17 20:37 UTC, DmitryKhiliuk commented
bookId-error.png опять undefined в крошках, хотя локально все хорошо. Буду исправлять.

2023-02-17 20:39 UTC, klichkovskiy requested changes

2023-02-17 20:39 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +                {status!=='loading'&&<div className={styles.breadCrumbs}>
![image](https://user-images.githubusercontent.com/62481116/219788253-57df654a-5faf-45b6-b5c5-053000f88850.png)
Жанр должен быть. Посмотри еще раз макет

2023-02-17 20:57 UTC, DmitryKhiliuk commented on src/pages/book/book-page.tsx
> +                {status!=='loading'&&<div className={styles.breadCrumbs}>
![BC](https://user-images.githubusercontent.com/89749062/219791596-97576f1b-79c0-4fea-ad24-d19b121b2b61.jpg)

В локальных тестах все нормально отображается.

2023-02-17 21:44 UTC, klichkovskiy approved these changes

2023-02-17 22:33 UTC, merged