modal booking
ClevertecFrontendLab/DmitryKhiliuk pull request #5
Opened 2023-03-13 21:27 UTC by DmitryKhiliuk

2023-03-13 21:32 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 25.
Количество непройденных тестов: 25.

2023-03-17 07:02 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 25.
Количество непройденных тестов: 25.

2023-03-17 22:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 4%.
Общее количество тестов: 25.
Количество непройденных тестов: 24.

2023-03-19 06:32 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 4%.
Общее количество тестов: 25.
Количество непройденных тестов: 24.

2023-03-20 04:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 92%.
Общее количество тестов: 25.
Количество непройденных тестов: 2.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/13-booking-edit-modal-view.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/9-today-is-sunday.png)
***
**booking and book rate -- booking edit modal -- check booking edit modal booking days (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20booking%20edit%20modal%20booking%20days%20(failed).png)
***
**booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679285801/edit-mobile-view.png)

2023-03-20 04:22 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 92%.
Общее количество тестов: 25.
Количество непройденных тестов: 2.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/13-booking-edit-modal-view.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/9-today-is-sunday.png)
***
**booking and book rate -- booking edit modal -- check booking edit modal booking days (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20booking%20edit%20modal%20booking%20days%20(failed).png)
***
**booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679286178/edit-mobile-view.png)

2023-03-20 04:29 UTC, DmitryKhiliuk commented
![13-booking-edit-modal-view (5)](https://user-images.githubusercontent.com/89749062/226247252-315ddcc2-5ab6-441e-978a-a2c0d51f5e43.png)
![14-modal-edited-date (5)](https://user-images.githubusercontent.com/89749062/226247263-f672391d-5868-491e-b904-a1914bd6c03f.png)

2023-03-20 04:32 UTC, DmitryKhiliuk commented
![all](https://user-images.githubusercontent.com/89749062/226247575-c2581069-fe50-4c75-8a99-69d18c694509.jpg)

2023-03-20 06:39 UTC, Gaurrus requested changes

2023-03-20 06:39 UTC, Gaurrus commented on src/components/buttons/button-comment.tsx
> +    const dateForButton = `${day}.${month}` */
убираей комментарии

2023-03-20 06:39 UTC, Gaurrus commented on src/components/calendar/calendar.tsx
> +    }
вот эту всю логику вычисления нужной даты нужно вынести в утилиты

2023-03-20 06:39 UTC, Gaurrus commented on src/components/header/header.tsx
> +                {rate==='failed'&&<Error styleWind='error' text='Оценка не была отправлена. Попробуйте позже!'/>}
тексты хотябы в константы вынеси

2023-03-20 06:39 UTC, Gaurrus commented on src/components/modal/modal.tsx
> +        <div className={cn(styles.main,( content === 'booking' || content === 'rate') && styles.mainBooking)} /* data-test-id='auth' */ data-test-id='modal-outer' onClick={onClickHandler} onKeyDown={
спрятался закомментированные код

2023-03-20 06:39 UTC, Gaurrus commented on src/components/rating/rating-for-modal.tsx
> +export const RatingForModal = ({getRating, count}: RatingForModalType) => {
![image](https://user-images.githubusercontent.com/85307211/226263820-91e55147-c173-47b4-a8f6-336c0ff69286.png)
че то у тебя дофига разных рейтингов, нельзя сделать один и в зависимсти от того где он отображается менять стили

2023-03-20 06:39 UTC, Gaurrus commented on src/components/snackbar/error.module.scss
> +    border: 1.5px solid #00CA71;
я понимаю что в дизайне так, но border 1.5px быть не может)

2023-03-20 06:39 UTC, Gaurrus commented on src/pages/book/book-page.tsx
> +    }
через useEffect надо бы

2023-03-20 06:39 UTC, Gaurrus commented on src/redux/books-reducer.ts
> +
убираем

2023-03-20 08:41 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 88%.
Общее количество тестов: 25.
Количество непройденных тестов: 3.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/13-booking-edit-modal-view.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/9-today-is-sunday.png)
***
**booking and book rate -- booking buttons view -- check buttons on book info pages (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/booking%20and%20book%20rate%20--%20booking%20buttons%20view%20--%20check%20buttons%20on%20book%20info%20pages%20(failed).png)
***
**booking and book rate -- booking edit modal -- check booking edit modal booking days (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20booking%20edit%20modal%20booking%20days%20(failed).png)
***
**booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/DmitryKhiliuk/1679301681/edit-mobile-view.png)

2023-03-20 08:54 UTC, Gaurrus approved these changes

2023-03-20 08:54 UTC, Gaurrus commented on src/components/rating/rating-for-modal.module.scss
> +            margin-right: 8.67px;
пиксель не бывает дробным - для отступов не сработает такая запись

2023-03-20 08:55 UTC, merged